chore: Fix typo.
Fix template typo with Ratel ingress introduced in #73.

    $ helm lint charts/dgraph
    ==> Linting charts/dgraph
    [ERROR] templates/: parse error at (dgraph/templates/ratel/ingress.yaml:49): unexpected {{end}}

    Error: 1 chart(s) linted, 1 chart(s) failed