fix: Configure no-persistence emptyDir correctly.
The helm installation fails when persistence is disabled. e.g., setting either
alpha.persistence.enabled or zero.persistence.enabled to false.

    $ helm install dev dgraph/dgraph --set alpha.persistence.enabled=false,zero.persistence.enabled=false
    Error: YAML parse error on dgraph/templates/alpha/statefulset.yaml: error converting YAML to JSON: yaml: line 88: did not find expected key

The cause for this error can be seen when rendering the template. The emptyDir
config gets mangled with the configMap:

    - name: config-volume
      configMap:
        name: dev-dgraph-alpha-config
      - name: datadir
        emptyDir: {}
    Error: YAML parse error on dgraph/templates/alpha/statefulset.yaml: error converting YAML to JSON: yaml: line 88: did not find expected key
    helm.go:81: [debug] error converting YAML to JSON: yaml: line 88: did not find expected key

This change sets the emptyDir config in the volumes section for datadir.

Resolves https://discuss.dgraph.io/t/helm-chart-deployment-fails-when-persistence-is-disabled/12240